/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Usuario;
import Modelo.UsuarioDAO;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.HeadlessException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class JFrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form JFrmLogin
     */
    public String usuario="";
    
    public JFrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLblUsuario = new javax.swing.JLabel();
        JTxtUsuario = new javax.swing.JTextField();
        JLblPassword = new javax.swing.JLabel();
        JPfPassword = new javax.swing.JPasswordField();
        JBtnAcceder = new javax.swing.JButton();
        JLblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login: Sistema Universitario");
        setResizable(false);

        JLblUsuario.setText("Usuario");

        JLblPassword.setText("Password");

        JBtnAcceder.setText("Acceder");
        JBtnAcceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAccederActionPerformed(evt);
            }
        });

        JLblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JLblTitle.setText("Sistema Universitario");

        jLabel1.setText("¿Olvidó su contraseña? ");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBtnAcceder))
                    .addComponent(JLblUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTxtUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLblPassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPfPassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLblTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(JLblTitle)
                .addGap(54, 54, 54)
                .addComponent(JLblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLblPassword)
                .addGap(12, 12, 12)
                .addComponent(JPfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JBtnAcceder))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAccederActionPerformed
        if (JTxtUsuario.getText().trim().isEmpty() || JPfPassword.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NO PUEDEN HABER CAMPOS VACIOS", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Usuario usuarioAConsultar = new Usuario();
                UsuarioDAO usuarioDAO = new UsuarioDAO();
                usuarioAConsultar.setUsername(JTxtUsuario.getText().trim());
                // Recuperación de información a través de otro objeto
                usuarioAConsultar = usuarioDAO.query(usuarioAConsultar);

                if (JPfPassword.getText().equals(usuarioAConsultar.getPassword()) && JTxtUsuario.getText().equals(usuarioAConsultar.getUsername())) {
                    
                    //MDI_Components mdi_componentes = new MDI_Components();
                    //mdi_componentes.setUsuario(usuarioAConsultar.getUsername());
                    
                    JOptionPane.showMessageDialog(null, "Bienvenido\n", "Mensaje de bienvenida", JOptionPane.INFORMATION_MESSAGE);

                    JFrmMDI menuGeneral = new JFrmMDI();
                    menuGeneral.setVisible(true);
                    usuario = JTxtUsuario.getText();
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "ERROR AL ENCONTRAR USUARIO o CONTRASEÑA", "ERROR", JOptionPane.ERROR_MESSAGE);
                    JPfPassword.setText("");
                    JTxtUsuario.setText("");
                }
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, "ERROR AL ENCONTRAR USUARIO o CONTRASEÑA", "ERROR", JOptionPane.ERROR_MESSAGE);
                JPfPassword.setText("");
                JTxtUsuario.setText("");
            } catch (UnknownHostException ex) {
                Logger.getLogger(JFrmLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_JBtnAccederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //CAMBIANDO LA INTERFAZ POR DEFECTO DE NETBEANS
        try{
            UIManager.setLookAndFeel(new FlatDarkLaf());
        }
        catch(Exception ex){
            System.out.println(ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAcceder;
    private javax.swing.JLabel JLblPassword;
    private javax.swing.JLabel JLblTitle;
    private javax.swing.JLabel JLblUsuario;
    private javax.swing.JPasswordField JPfPassword;
    private javax.swing.JTextField JTxtUsuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
