/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.JFrmBuscaFacultad;
import Modelo.FacultadDAO;
import Controlador.Facultad;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class JIntFrmMantFacultades extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIntFrmMantFacultades
     */
    public JIntFrmMantFacultades() throws SQLException {
        initComponents();
        llenar_tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroupEF = new javax.swing.ButtonGroup();
        JPanelInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JPanEstFacultad = new javax.swing.JPanel();
        JRBActivo = new javax.swing.JRadioButton();
        JRBInactivo = new javax.swing.JRadioButton();
        JTxtCodFacultad = new javax.swing.JTextField();
        JTxtNomFacultad = new javax.swing.JTextField();
        JPanelAcciones = new javax.swing.JPanel();
        CmdRegistrar = new javax.swing.JButton();
        CmdModificar = new javax.swing.JButton();
        CmdBuscar = new javax.swing.JButton();
        CmdLimpiar = new javax.swing.JButton();
        CmdEliminar = new javax.swing.JButton();
        JTxtBuscar = new javax.swing.JTextField();
        CmdMas = new javax.swing.JButton();
        CmdAyuda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableDataFacu = new javax.swing.JTable();

        setClosable(true);
        setTitle("Mantenimiento Facultades");
        setToolTipText("Mantenimiento de Facultades");

        JPanelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de Facultad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("Código Facultad:");

        jLabel2.setText("Nombre Facultad:");

        JPanEstFacultad.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado Facultad"));

        BtnGroupEF.add(JRBActivo);
        JRBActivo.setText("Activa");

        BtnGroupEF.add(JRBInactivo);
        JRBInactivo.setText("Inactiva");

        javax.swing.GroupLayout JPanEstFacultadLayout = new javax.swing.GroupLayout(JPanEstFacultad);
        JPanEstFacultad.setLayout(JPanEstFacultadLayout);
        JPanEstFacultadLayout.setHorizontalGroup(
            JPanEstFacultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanEstFacultadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JRBActivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JRBInactivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanEstFacultadLayout.setVerticalGroup(
            JPanEstFacultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanEstFacultadLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(JPanEstFacultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRBActivo)
                    .addComponent(JRBInactivo))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPanelInfoLayout = new javax.swing.GroupLayout(JPanelInfo);
        JPanelInfo.setLayout(JPanelInfoLayout);
        JPanelInfoLayout.setHorizontalGroup(
            JPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelInfoLayout.createSequentialGroup()
                .addGroup(JPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelInfoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(JPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTxtNomFacultad, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(JTxtCodFacultad)))
                    .addGroup(JPanelInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JPanEstFacultad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JPanelInfoLayout.setVerticalGroup(
            JPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelInfoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(JPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTxtCodFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTxtNomFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JPanEstFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanelAcciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        CmdRegistrar.setText("Registrar");
        CmdRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CmdRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdRegistrarActionPerformed(evt);
            }
        });

        CmdModificar.setText("Modificar");
        CmdModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CmdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdModificarActionPerformed(evt);
            }
        });

        CmdBuscar.setText("Buscar");
        CmdBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdBuscarActionPerformed(evt);
            }
        });

        CmdLimpiar.setText("Limpiar");
        CmdLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdLimpiarActionPerformed(evt);
            }
        });

        CmdEliminar.setText("Eliminar");
        CmdEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdEliminarActionPerformed(evt);
            }
        });

        JTxtBuscar.setToolTipText("Puede ingresar el código de la facultad o bien presionar el botón de puntos suspensivos (...) para hacer más fácil su búsqueda");

        CmdMas.setText("...");
        CmdMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CmdMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdMasActionPerformed(evt);
            }
        });

        CmdAyuda.setText("Ayuda");
        CmdAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelAccionesLayout = new javax.swing.GroupLayout(JPanelAcciones);
        JPanelAcciones.setLayout(JPanelAccionesLayout);
        JPanelAccionesLayout.setHorizontalGroup(
            JPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAccionesLayout.createSequentialGroup()
                .addGroup(JPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelAccionesLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(JPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CmdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPanelAccionesLayout.createSequentialGroup()
                                .addComponent(JTxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmdMas))))
                    .addGroup(JPanelAccionesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(JPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CmdEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CmdRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CmdModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CmdLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPanelAccionesLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(CmdAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        JPanelAccionesLayout.setVerticalGroup(
            JPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAccionesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(JPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmdMas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmdBuscar)
                .addGap(31, 31, 31)
                .addGroup(JPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmdRegistrar)
                    .addComponent(CmdModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmdEliminar)
                    .addComponent(CmdLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmdAyuda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTableDataFacu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Estado"
            }
        ));
        jScrollPane1.setViewportView(JTableDataFacu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanelAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPanelAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void llenar_tabla() throws SQLException {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Estado");
        FacultadDAO facultadDAO = new FacultadDAO();
        List<Facultad> facultades = facultadDAO.select();
        JTableDataFacu.setModel(modelo);
        String[] dato = new String[3];
        for (int i = 0; i < facultades.size(); i++) {
            dato[0] = facultades.get(i).getCodigo_facultad();
            dato[1] = facultades.get(i).getNombre_facultad();
            dato[2] = facultades.get(i).getEstado_facultad();
            modelo.addRow(dato);
        }
    }

    private void CmdMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdMasActionPerformed
        JFrmBuscaFacultad jfrm_buscarfacultad = new JFrmBuscaFacultad();
        jfrm_buscarfacultad.setVisible(true);
    }//GEN-LAST:event_CmdMasActionPerformed

    private void CmdRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdRegistrarActionPerformed
        Facultad facultad = new Facultad();
        FacultadDAO facultadDAO = new FacultadDAO();

        if (JTxtCodFacultad.getText().length() != 0 && JTxtNomFacultad.getText().length() != 0) {
            String codigo_facultad = JTxtCodFacultad.getText();
            String nombre_facultad = JTxtNomFacultad.getText();

            facultad.setCodigo_facultad(codigo_facultad);
            facultad.setNombre_facultad(nombre_facultad);

            if (JRBActivo.isSelected()) {
                facultad.setEstado_facultad("A");
            } else {
                facultad.setEstado_facultad("I");
            }

            facultadDAO.insert(facultad);

            try {
                llenar_tabla();
            } catch (SQLException ex) {
                Logger.getLogger(JIntFrmMantFacultades.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Hay campos vacíos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CmdRegistrarActionPerformed

    private void CmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdLimpiarActionPerformed
        JTxtCodFacultad.setText("");
        JTxtNomFacultad.setText("");
        BtnGroupEF.clearSelection();
    }//GEN-LAST:event_CmdLimpiarActionPerformed

    private void CmdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdModificarActionPerformed
        Facultad facultad = new Facultad();
        FacultadDAO facultadDAO = new FacultadDAO();

        if (JTxtCodFacultad.getText().length() != 0 && JTxtNomFacultad.getText().length() != 0) {
            String codigo_facultad = JTxtCodFacultad.getText();
            String nombre_facultad = JTxtNomFacultad.getText();

            facultad.setCodigo_facultad(codigo_facultad);
            facultad.setNombre_facultad(nombre_facultad);

            if (JRBActivo.isSelected()) {
                facultad.setEstado_facultad("A");
            } else {
                facultad.setEstado_facultad("I");
            }

            facultadDAO.update(facultad);

            try {
                llenar_tabla();
            } catch (SQLException ex) {
                Logger.getLogger(JIntFrmMantFacultades.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Hay campos vacíos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CmdModificarActionPerformed

    private void CmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdEliminarActionPerformed
        Facultad facultad = new Facultad();
        FacultadDAO facultadDAO = new FacultadDAO();

        if (JTxtCodFacultad.getText().length() != 0 && JTxtNomFacultad.getText().length() != 0) {
            String codigo_facultad = JTxtCodFacultad.getText();

            facultad.setCodigo_facultad(codigo_facultad);

            facultadDAO.delete(facultad);

            try {
                llenar_tabla();
            } catch (SQLException ex) {
                Logger.getLogger(JIntFrmMantFacultades.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Hay campos vacíos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CmdEliminarActionPerformed

    private void CmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdBuscarActionPerformed
        Facultad facultad = new Facultad();
        FacultadDAO facultadDAO = new FacultadDAO();
        facultad.setCodigo_facultad(JTxtBuscar.getText());

        facultad = facultadDAO.query(facultad);

        JTxtCodFacultad.setText(facultad.getCodigo_facultad());
        JTxtNomFacultad.setText(facultad.getNombre_facultad());
        String val_estatus = facultad.getEstado_facultad();
        if (val_estatus.equals("A")) {
            JRBActivo.setSelected(true);
        } else {
            JRBInactivo.setSelected(true);
        }
    }//GEN-LAST:event_CmdBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGroupEF;
    private javax.swing.JButton CmdAyuda;
    private javax.swing.JButton CmdBuscar;
    private javax.swing.JButton CmdEliminar;
    private javax.swing.JButton CmdLimpiar;
    private javax.swing.JButton CmdMas;
    private javax.swing.JButton CmdModificar;
    private javax.swing.JButton CmdRegistrar;
    private javax.swing.JPanel JPanEstFacultad;
    private javax.swing.JPanel JPanelAcciones;
    private javax.swing.JPanel JPanelInfo;
    private javax.swing.JRadioButton JRBActivo;
    private javax.swing.JRadioButton JRBInactivo;
    private javax.swing.JTable JTableDataFacu;
    private javax.swing.JTextField JTxtBuscar;
    private javax.swing.JTextField JTxtCodFacultad;
    private javax.swing.JTextField JTxtNomFacultad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
